# Site settings
title: Nat's Cloud Portfolio
description: Professional portfolio showcasing cloud architecture expertise and infrastructure as code
url: https://ncasterism.github.io
baseurl: /NatsCloudPlayground

# Theme settings - using a simpler theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Author information
author:
  name: Nat
  email: your-email@example.com
  linkedin: https://linkedin.com/in/yourprofile
  github: https://github.com/ncasterism

# Build settings
markdown: kramdown
highlighter: rouge

# Explicitly set which files jekyll will read
include:
  - "*.html"
  - "*.md"
  - "_layouts"
  - "_includes"
  - "assets"
  - "blog"
  - "timeline"
  - "certifications"
  - "presentations"

# Navigation
header_pages:
  - blog/index.md
  - timeline/timeline.md
  - certifications/index.md
  - presentations/index.md

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default" 