name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # Build the Jekyll site
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Jekyll
        run: |
          gem install jekyll bundler
      - name: Build site
        run: jekyll build --source docs --destination _site

      # Check for broken links in the generated site
      - name: Install Python Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install link checker
        run: pip install markdown linkchecker
      - name: Check Broken Links
        run: linkchecker _site

      # Upload the generated site for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './_site'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v1
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1